//! Task audit log — persists a record of every job the agent completed for
//! its human owner. Used by the mobile app to surface shareable moments.
//!
//! Schema is intentionally minimal: the agent writes only metadata (category,
//! outcome, amount, duration, one-sentence summary). No task content, no
//! requester identity, no personal data from the phone.

use rusqlite::{params, Connection};
use serde::{Deserialize, Serialize};
use std::sync::Mutex;

// ── Types ────────────────────────────────────────────────────────────────────

/// A single entry in the task audit log.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskLogEntry {
    pub id: i64,
    /// Unix timestamp (seconds) when the entry was written.
    pub timestamp: i64,
    /// Broad task category: "research", "code", "writing", "trade", "data", "other".
    pub category: String,
    /// Terminal outcome: "delivered", "disputed", "cancelled".
    pub outcome: String,
    /// Agreed task price in USD (may be 0 if unpaid / disputed).
    pub amount_usd: f64,
    /// Wall-clock minutes from PROPOSE accepted to DELIVER sent.
    pub duration_min: u32,
    /// One-sentence human-readable summary generated by the agent.
    /// Must describe task *type* only — never content, requester identity,
    /// or any personal data accessed during execution.
    pub summary: String,
    /// True once the owner has posted this entry to a social platform.
    pub shared: bool,
}

/// Fields supplied by the agent when writing a new entry.
#[derive(Debug, Deserialize)]
pub struct NewTaskLogEntry {
    pub category: String,
    pub outcome: String,
    #[serde(default)]
    pub amount_usd: f64,
    #[serde(default)]
    pub duration_min: u32,
    pub summary: String,
}

// ── Store ─────────────────────────────────────────────────────────────────────

pub struct TaskLog {
    conn: Mutex<Connection>,
}

impl TaskLog {
    pub fn open(path: &std::path::Path) -> anyhow::Result<Self> {
        let conn = Connection::open(path)?;
        conn.execute_batch(
            "PRAGMA journal_mode=WAL;
             CREATE TABLE IF NOT EXISTS task_log (
                 id           INTEGER PRIMARY KEY AUTOINCREMENT,
                 timestamp    INTEGER NOT NULL,
                 category     TEXT    NOT NULL,
                 outcome      TEXT    NOT NULL,
                 amount_usd   REAL    NOT NULL DEFAULT 0,
                 duration_min INTEGER NOT NULL DEFAULT 0,
                 summary      TEXT    NOT NULL,
                 shared       INTEGER NOT NULL DEFAULT 0
             );
             CREATE INDEX IF NOT EXISTS idx_task_log_ts ON task_log(id DESC);",
        )?;
        Ok(Self { conn: Mutex::new(conn) })
    }

    pub fn open_in_memory() -> anyhow::Result<Self> {
        let conn = Connection::open_in_memory()?;
        conn.execute_batch(
            "CREATE TABLE IF NOT EXISTS task_log (
                 id           INTEGER PRIMARY KEY AUTOINCREMENT,
                 timestamp    INTEGER NOT NULL,
                 category     TEXT    NOT NULL,
                 outcome      TEXT    NOT NULL,
                 amount_usd   REAL    NOT NULL DEFAULT 0,
                 duration_min INTEGER NOT NULL DEFAULT 0,
                 summary      TEXT    NOT NULL,
                 shared       INTEGER NOT NULL DEFAULT 0
             );",
        )?;
        Ok(Self { conn: Mutex::new(conn) })
    }

    /// Insert a new entry. Returns the new row id.
    pub fn insert(&self, entry: &NewTaskLogEntry) -> anyhow::Result<i64> {
        let ts = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs() as i64;
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "INSERT INTO task_log
             (timestamp, category, outcome, amount_usd, duration_min, summary, shared)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, 0)",
            params![
                ts,
                entry.category,
                entry.outcome,
                entry.amount_usd,
                entry.duration_min,
                entry.summary,
            ],
        )?;
        Ok(conn.last_insert_rowid())
    }

    /// Return entries newest-first, with optional cursor-based pagination.
    pub fn list(&self, limit: u32, before_id: Option<i64>) -> anyhow::Result<Vec<TaskLogEntry>> {
        let conn = self.conn.lock().unwrap();
        let entries = if let Some(bid) = before_id {
            let mut stmt = conn.prepare(
                "SELECT id, timestamp, category, outcome, amount_usd, duration_min, summary, shared
                 FROM task_log WHERE id < ?1 ORDER BY id DESC LIMIT ?2",
            )?;
            let rows = stmt.query_map(params![bid, limit], map_row)?
                .collect::<Result<Vec<_>, _>>()?;
            rows
        } else {
            let mut stmt = conn.prepare(
                "SELECT id, timestamp, category, outcome, amount_usd, duration_min, summary, shared
                 FROM task_log ORDER BY id DESC LIMIT ?1",
            )?;
            let rows = stmt.query_map(params![limit], map_row)?
                .collect::<Result<Vec<_>, _>>()?;
            rows
        };
        Ok(entries)
    }

    /// Mark an entry as shared (posted to socials). Returns false if not found.
    pub fn mark_shared(&self, id: i64) -> anyhow::Result<bool> {
        let conn = self.conn.lock().unwrap();
        let n = conn.execute(
            "UPDATE task_log SET shared = 1 WHERE id = ?1",
            params![id],
        )?;
        Ok(n > 0)
    }

    /// Delete an entry (owner privacy control). Returns false if not found.
    pub fn delete(&self, id: i64) -> anyhow::Result<bool> {
        let conn = self.conn.lock().unwrap();
        let n = conn.execute("DELETE FROM task_log WHERE id = ?1", params![id])?;
        Ok(n > 0)
    }

    /// Total number of delivered tasks — shown on the agent card.
    pub fn delivered_count(&self) -> anyhow::Result<u64> {
        let conn = self.conn.lock().unwrap();
        let n: i64 = conn.query_row(
            "SELECT COUNT(*) FROM task_log WHERE outcome = 'delivered'",
            [],
            |r| r.get(0),
        )?;
        Ok(n as u64)
    }
}

fn map_row(row: &rusqlite::Row) -> rusqlite::Result<TaskLogEntry> {
    Ok(TaskLogEntry {
        id: row.get(0)?,
        timestamp: row.get(1)?,
        category: row.get(2)?,
        outcome: row.get(3)?,
        amount_usd: row.get(4)?,
        duration_min: row.get::<_, i32>(5)? as u32,
        summary: row.get(6)?,
        shared: row.get::<_, i32>(7)? != 0,
    })
}
